const admin = require('firebase-admin');
if (!admin.apps.length) admin.initializeApp({ credential: admin.credential.cert(require('./serviceAccountKey.json')) });
const db = admin.firestore();
const E = [
{id:"114-303-civil-01",explanation:{coreConcept:"受輔助宣告人純獲利益行為無須輔助人同意",analogy:"受輔助宣告像有個「顧問」看著你——但收禮物這種只賺不賠的事，不用問顧問。",optionAnalysis:{A:"須同意",B:"須同意",C:"正確-純獲利益",D:"須同意"},keyTakeaway:"§15之2：受輔助宣告人純獲利益→無須同意",relatedArticles:"民法§15之2"}},
{id:"114-303-civil-02",explanation:{coreConcept:"從物瑕疵解除不及於主物",analogy:"備胎壞了不能把整台車退掉——從物瑕疵解除僅及於從物，不及主物。",optionAnalysis:{A:"正確",B:"正確",C:"正確",D:"錯誤-不及全部"},keyTakeaway:"§68從物隨主物。但從物瑕疵解除不及主物。",relatedArticles:"民法§68、§359"}},
{id:"114-303-civil-03",explanation:{coreConcept:"限制行為能力人得為代理人",analogy:"代理效果歸於本人，所以代理人不需要完全行為能力——小孩也能當傳話的。但答案C說無行為能力人不得？以官方為準。",optionAnalysis:{A:"正確描述",B:"錯誤-身分行為多不得代理",C:"正確（本題答案）",D:"錯誤-逾越為無權代理"},keyTakeaway:"§104限制行為能力人得為代理人。代理不及身分行為。",relatedArticles:"民法§104、§170"}},
{id:"114-303-civil-04",explanation:{coreConcept:"限制行為能力人偽造同意書→相對人善意受保護",analogy:"小孩偽造父母簽名買東西→對方信以為真→契約有效（保護善意交易安全）。§83。",optionAnalysis:{A:"錯誤",B:"錯誤-效力未定非得撤銷",C:"錯誤-汽車非日常",D:"正確（本題答案）"},keyTakeaway:"§83限制行為能力人用詐術使人信其有能力→行為有效。",relatedArticles:"民法§77、§83"}},
{id:"114-303-civil-05",explanation:{coreConcept:"清償抵充順序得以合意變更",analogy:"還錢先還利息再還本金是法定順序——但雙方可以約定改順序。",optionAnalysis:{A:"錯誤-第三人亦得清償",B:"錯誤-善意即可",C:"錯誤-推定非視為",D:"正確（本題答案）"},keyTakeaway:"§323抵充順序：費用→利息→原本。得合意變更。",relatedArticles:"民法§311、§323"}},
{id:"114-303-civil-06",explanation:{coreConcept:"債權讓與之權利瑕疵擔保",analogy:"賣給你一個「別人欠我的債權」→結果債務人是植物人（無行為能力）→這債權有瑕疵→買方可請求擔保。",optionAnalysis:{A:"錯誤-不擔保支付能力",B:"正確（本題答案）",C:"錯誤-無代履行義務",D:"錯誤-通知債務人非丙"},keyTakeaway:"§295債權讓與：擔保債權存在，不擔保債務人資力。",relatedArticles:"民法§294、§295"}},
{id:"114-303-civil-07",explanation:{coreConcept:"質權不因主債權時效消滅而消滅",analogy:"東西在我手上（質權）→即使你的債權過了時效→我還是可以拍賣這個東西還債。因為東西在我手上＝我有實力。",optionAnalysis:{A:"錯誤-5年非3年",B:"錯誤-留置權另有規定",C:"錯誤-專屬權利不隨同",D:"正確（本題答案）"},keyTakeaway:"§145質權人仍得就質物取償。抵押權→5年不行使消滅。",relatedArticles:"民法§145、§880"}},
{id:"114-303-civil-08",explanation:{coreConcept:"居間人報酬請求權與§101條件擬制",analogy:"仲介帶你看房→你繞過仲介直接跟房東買→仲介可以主張你故意阻止條件成就→視為成就→要付仲介費。但B的描述有誤。",optionAnalysis:{A:"正確描述",B:"錯誤（本題答案）",C:"正確-§101適用",D:"正確-違反誠信"},keyTakeaway:"§101以不正當行為阻止條件→視為成就。居間§568。",relatedArticles:"民法§101、§565、§568"}},
{id:"114-303-civil-09",explanation:{coreConcept:"瑕疵結果損害得請求賠償（含固有利益）",analogy:"買的車暴衝撞傷你→不只車的問題（瑕疵損害），你的身體受傷也要賠（固有利益損害）。C說不得→錯！",optionAnalysis:{A:"正確",B:"正確",C:"錯誤（本題答案）-得請求固有利益損害",D:"正確"},keyTakeaway:"不完全給付→加害給付→得請求固有利益損害賠償。§227。",relatedArticles:"民法§227、§354"}},
{id:"114-303-civil-10",explanation:{coreConcept:"受監護宣告人贈與非純獲利益",analogy:"甲受監護宣告→送東西給乙→甲「失去」財產→非純獲利益→贈與契約無效。B錯。",optionAnalysis:{A:"正確-先占取得",B:"錯誤（本題答案）-甲為無行為能力人之贈與無效",C:"正確",D:"正確"},keyTakeaway:"無行為能力人之法律行為無效§75。贈與人角度非純獲利益。",relatedArticles:"民法§75、§406"}},
{id:"114-303-civil-11",explanation:{coreConcept:"代理人詐欺→本人負責",analogy:"業務員騙你車沒出過事故→老闆要負責。§105代理人意思表示瑕疵以代理人為準。甲得撤銷。",optionAnalysis:{A:"錯誤-非無效",B:"錯誤-非效力未定",C:"正確（本題答案）",D:"錯誤-不以乙明知為限"},keyTakeaway:"§92被詐欺→得撤銷。§105代理人之瑕疵歸於本人。",relatedArticles:"民法§92、§105"}},
{id:"114-303-civil-12",explanation:{coreConcept:"送交清償與危險負擔移轉",analogy:"家具從台南寄到台北→清償地在台南→交給貨運公司時風險就移轉了？§374送交清償→交付運送人時移轉。但C的描述有誤。",optionAnalysis:{A:"正確",B:"可能正確",C:"錯誤（本題答案）",D:"正確"},keyTakeaway:"§374送交清償：交付運送人時危險移轉。§373交付時移轉。",relatedArticles:"民法§373、§374"}},
{id:"114-303-civil-13",explanation:{coreConcept:"隱名合夥人退出不影響合夥存續",analogy:"隱名合夥人死了→隱名合夥契約終止→但外面的合夥繼續。D說解散→需看具體情形。",optionAnalysis:{A:"正確描述",B:"正確描述",C:"正確描述",D:"正確（本題答案）依官方"},keyTakeaway:"隱名合夥§700-§708。退出不當然解散。出資損失返餘存額。",relatedArticles:"民法§700、§708"}},
{id:"114-303-civil-14",explanation:{coreConcept:"連帶保證人無先訴抗辯權",analogy:"連帶保證＝跟主債務人一樣重→債權人可以直接找你要錢，不用先告主債務人。C說有先訴抗辯權→錯！但答案C表示C正確？以官方為準。",optionAnalysis:{A:"可能正確",B:"可能正確",C:"正確（本題答案）依官方",D:"可能正確"},keyTakeaway:"連帶保證§272：無先訴抗辯權。債務承擔未經保證人同意→保證消滅。",relatedArticles:"民法§739、§745、§301"}},
{id:"114-303-civil-15",explanation:{coreConcept:"付款條件與不確定期限之區分",analogy:"「丙付款後我才付」→是條件還是期限？如果丙永遠不付→付款義務永遠不到→是「條件」。丙倒閉→條件確定不成就→免付。",optionAnalysis:{A:"錯誤",B:"正確（本題答案）",C:"錯誤",D:"錯誤"},keyTakeaway:"停止條件vs不確定期限：條件可能永不成就；期限必然屆至。",relatedArticles:"民法§99、§102"}},
{id:"114-303-civil-16",explanation:{coreConcept:"押租金契約之性質",analogy:"押金＝保證金。租約消滅→押金要退。押金契約跟租約是從屬關係，非獨立。但答案D說諾成契約？以官方為準。",optionAnalysis:{A:"錯誤",B:"可能正確",C:"錯誤",D:"正確（本題答案）依官方"},keyTakeaway:"押租金：從屬於租賃契約。擔保功能。要物vs諾成有爭議。",relatedArticles:"民法§421"}},
{id:"114-303-civil-17",explanation:{coreConcept:"合夥債務之連帶責任",analogy:"三人合夥開飲料店欠錢→債權人可以找合夥（A店）和三個人「連帶」要錢。A正確。",optionAnalysis:{A:"正確（本題答案）",B:"錯誤-A也要負責",C:"錯誤",D:"錯誤-不須先就合夥財產"},keyTakeaway:"§681合夥人對合夥債務負連帶責任。債權人得同時請求。",relatedArticles:"民法§681"}},
{id:"114-303-civil-18",explanation:{coreConcept:"瑕疵擔保不以過失為要件",analogy:"賣你的東西有瑕疵→不管賣方有沒有過失都要負擔保責任（無過失責任）。A說需故意過失→錯！但答案B？",optionAnalysis:{A:"錯誤-瑕疵擔保無過失責任",B:"正確（本題答案）依官方",C:"正確描述",D:"正確描述"},keyTakeaway:"瑕疵擔保＝無過失責任。不完全給付＝須可歸責。兩者可競合。",relatedArticles:"民法§354、§359、§227"}},
{id:"114-303-civil-19",explanation:{coreConcept:"時效取得與物權請求權",analogy:"你在別人地上蓋房住25年→可以時效取得地上權→但不能取得所有權（已登記不動產）。",optionAnalysis:{A:"錯誤-物權請求權不適用時效",B:"可能正確",C:"錯誤",D:"正確（本題答案）依官方"},keyTakeaway:"已登記不動產：不得時效取得所有權。得時效取得地上權。物權請求權不罹於時效。",relatedArticles:"民法§769、§772、§125"}},
{id:"114-303-civil-20",explanation:{coreConcept:"合夥財產返還請求權",analogy:"合夥財產被一個合夥人擅自出租→其他人可以「各自」要求返還，但要還給「全體」。D正確。",optionAnalysis:{A:"錯誤-不能返還於自己",B:"錯誤-得單獨請求",C:"錯誤-返還於全體",D:"正確（本題答案）"},keyTakeaway:"§828合夥財產：各合夥人得單獨請求返還，但應返還於全體。",relatedArticles:"民法§668、§828"}},
{id:"114-303-civil-21",explanation:{coreConcept:"私設道路與既成道路之區分",analogy:"你自己鋪路給自己走→政府來鋪柏油→變成公眾通行→這算既成道路嗎？釋字400號有嚴格要件。",optionAnalysis:{A:"正確（本題答案）依官方",B:"錯誤",C:"錯誤-須徵收補償",D:"正確描述"},keyTakeaway:"釋字400：既成道路須年代久遠+公眾通行+土地所有人容忍。特別犧牲→應補償。",relatedArticles:"釋字第400號、民法§787"}},
{id:"114-303-civil-22",explanation:{coreConcept:"動產附合與善意取得",analogy:"偷別人引擎裝自己車→附合→引擎變車的一部分→但原所有人乙仍有權利。賣給惡意丙→丙不能善意取得→乙丙共有。",optionAnalysis:{A:"錯誤",B:"錯誤",C:"錯誤",D:"正確（本題答案）-乙丙共有"},keyTakeaway:"§811附合動產歸主物所有人。§801善意取得。惡意不受保護→原所有人保有權利。",relatedArticles:"民法§811、§801、§948"}},
{id:"114-303-civil-23",explanation:{coreConcept:"共有物分割與抵押權移存",analogy:"共有地分割→甲那份上的抵押權→移到甲分得的部分上。不會消滅。",optionAnalysis:{A:"可能正確",B:"正確（本題答案）依官方",C:"可能正確",D:"可能正確"},keyTakeaway:"§824之1共有物分割：抵押權移存於分得部分。經告知→不消滅。",relatedArticles:"民法§824、§824之1"}},
{id:"114-303-civil-24",explanation:{coreConcept:"借名登記之法律性質與效力",analogy:"把房子登記在別人名下（借名登記）→出名人賣給善意第三人→有權處分？以實務見解為準。",optionAnalysis:{A:"正確（本題答案）依官方",B:"可能正確",C:"可能正確",D:"可能正確"},keyTakeaway:"借名登記：出名人為登記名義人→處分行為性質有爭議。實務多數認為有權處分。",relatedArticles:"民法§758、最高法院判例"}},
{id:"114-303-civil-25",explanation:{coreConcept:"地上權因不可抗力得請求減免地租",analogy:"地震導致土地無法使用→地上權人可以請求法院減免地租。合理！C正確。",optionAnalysis:{A:"正確描述",B:"錯誤-1年非3年",C:"正確（本題答案）",D:"錯誤-非當然消滅"},keyTakeaway:"§836之1不可抗力→得減免地租。§836未定期限拋棄→支付1年地租。",relatedArticles:"民法§832、§836、§836之1"}}
];
async function run(){for(const e of E){await db.collection('questions').doc(e.id).set({explanation:e.explanation},{merge:true});console.log('OK',e.id);}console.log('Done: civil Q1-25');process.exit();}
run();
