const admin = require('firebase-admin');
if (!admin.apps.length) admin.initializeApp({ credential: admin.credential.cert(require('./serviceAccountKey.json')) });
const db = admin.firestore();
const E = [
{id:"114-303-civil-26",explanation:{coreConcept:"地上權使用方法之約定非經登記不得對抗第三人",analogy:"地上權怎麼用有約定→但沒登記→新買家不受拘束。要對抗第三人必須登記。",optionAnalysis:{A:"正確描述",B:"錯誤-無30年上限",C:"正確（本題答案）依官方",D:"錯誤"},keyTakeaway:"§836之2使用方法約定→須登記始對抗第三人。區分地上權§841之1。",relatedArticles:"民法§836之2、§841之1"}},
{id:"114-303-civil-27",explanation:{coreConcept:"權利質權標的之限制",analogy:"股票可以質押→但股份有限公司「股票」本身是有價證券，適用動產質權非權利質權？A正確→股票非權利質權標的。",optionAnalysis:{A:"正確（本題答案）-股票為動產質權",B:"可設定",C:"錯誤-銀幣為動產非權利",D:"可設定"},keyTakeaway:"權利質權§900：以可讓與之債權或其他權利為標的。股票→動產質權。",relatedArticles:"民法§900、§908"}},
{id:"114-303-civil-28",explanation:{coreConcept:"營業質權之流質特約",analogy:"當鋪（營業質）→到期不贖→當鋪可以直接取得所有權→但不足額部分債權仍存在？C正確依官方。",optionAnalysis:{A:"錯誤",B:"錯誤",C:"正確（本題答案）依官方",D:"錯誤"},keyTakeaway:"§899之2營業質：取贖期滿未贖→質權人得處分。不足額→債權未消滅。",relatedArticles:"民法§899之2"}},
{id:"114-303-civil-29",explanation:{coreConcept:"抵押權設定後之地上權與併付拍賣",analogy:"先設抵押→後設地上權蓋房→拍賣土地沒人要→可以把房子一起拍，但房子的錢抵押權人不能優先拿。但答案B？",optionAnalysis:{A:"錯誤-得設定",B:"正確（本題答案）依官方",C:"可能正確",D:"錯誤"},keyTakeaway:"§866抵押權設定後之地上權→不影響抵押權。§877併付拍賣。",relatedArticles:"民法§866、§877"}},
{id:"114-303-civil-30",explanation:{coreConcept:"典權期滿不贖之絕賣條款",analogy:"典權像古代的「活賣」→期滿不贖→看有沒有絕賣條款。有→典權人取得所有權。但絕賣未登記→效力？C說仍取得→有誤。",optionAnalysis:{A:"正確描述",B:"正確描述",C:"錯誤（本題答案）-未登記不得對抗",D:"正確描述"},keyTakeaway:"§923典權絕賣條款未登記→不得對抗第三人。期滿不贖→§924找贖。",relatedArticles:"民法§911、§923、§924"}},
{id:"114-303-civil-31",explanation:{coreConcept:"惡意占有人之費用償還請求權",analogy:"小偷偷了古董車→花大錢鍍金→能不能向原主要鍍金費？惡意占有人的「奢侈費用」不得請求。但答案A？",optionAnalysis:{A:"正確（本題答案）依官方",B:"正確描述",C:"錯誤-奢侈費不得請求",D:"正確描述"},keyTakeaway:"§955惡意占有人：得請求有益費用（增值部分）。不得請求奢侈費。",relatedArticles:"民法§952-§957"}},
{id:"114-303-civil-32",explanation:{coreConcept:"成年年齡修正對身分法之影響",analogy:"成年18歲→收養年齡差距也跟著調整。夫妻一方收養他方子女→長16歲以上。A正確。",optionAnalysis:{A:"正確（本題答案）",B:"錯誤-18歲即成年不需同意",C:"錯誤-長20歲",D:"錯誤-17歲"},keyTakeaway:"§1073收養：長被收養者20歲。夫妻一方收養他方子女→長16歲。",relatedArticles:"民法§12、§1073"}},
{id:"114-303-civil-33",explanation:{coreConcept:"雙方均有過失之離婚贍養費",analogy:"雙方都外遇→乙也有過錯→乙請求贍養費→但乙自己也有過失→能否請求？B說不能→依官方。",optionAnalysis:{A:"正確",B:"正確（本題答案-何者錯誤）依官方",C:"正確",D:"正確"},keyTakeaway:"§1057贍養費：判決離婚+無過失方+生活困難。雙方均有過失→不得請求。",relatedArticles:"民法§1052、§1056、§1057"}},
{id:"114-303-civil-34",explanation:{coreConcept:"死亡宣告撤銷後之婚姻效力",analogy:"老公被宣告死亡→老婆再嫁→老公回來了！如果老婆和新老公都「善意」→後婚有效，前婚消滅。A正確。",optionAnalysis:{A:"正確（本題答案）",B:"錯誤-須雙方善意",C:"錯誤",D:"錯誤"},keyTakeaway:"§988死亡宣告撤銷：雙方善意→後婚有效→前婚消滅。一方惡意→後婚無效。",relatedArticles:"民法§9、§988"}},
{id:"114-303-civil-35",explanation:{coreConcept:"親權人對子女財產之管理使用處分",analogy:"爸爸管小孩的腳踏車→可以管理、可以使用（供教養需要）、但不能隨便賣掉。B說自由處分→錯？但答案C？",optionAnalysis:{A:"正確",B:"錯誤-不得自由處分",C:"正確（本題答案-何者錯誤）依官方",D:"正確"},keyTakeaway:"§1088親權人管理子女財產：管理✓使用✓（但有限制）處分需為子女利益。",relatedArticles:"民法§1088"}},
{id:"114-303-civil-36",explanation:{coreConcept:"子女姓氏約定不成之處理",analogy:"爸媽對小孩姓什麼講不攏→抽籤！不是找法院。§1059第1項：於戶政事務所抽籤決定。A正確。",optionAnalysis:{A:"正確（本題答案-不得請求法院）",B:"得請求法院",C:"得請求法院",D:"得請求法院"},keyTakeaway:"§1059姓氏約定不成→抽籤。重大事項不一致→法院酌定。住所不一致→法院酌定。",relatedArticles:"民法§1059、§1089"}},
{id:"114-303-civil-37",explanation:{coreConcept:"剩餘財產分配之範圍",analogy:"離婚分財產→婚後賺的才算→但改用法定財產制「前」的薪資→不算。C正確。",optionAnalysis:{A:"屬於分配範圍",B:"屬於分配範圍",C:"正確（本題答案-非屬）",D:"屬於分配範圍"},keyTakeaway:"§1030之1：婚後財產扣除婚後債務＝剩餘。改用前所得不計入。",relatedArticles:"民法§1030之1"}},
{id:"114-303-civil-38",explanation:{coreConcept:"法院調解離婚之生效時點",analogy:"法院調解成立→當場生效→不用再去登記才算。A正確。",optionAnalysis:{A:"正確（本題答案）",B:"錯誤",C:"錯誤",D:"錯誤"},keyTakeaway:"調解離婚→成立時消滅。協議離婚→登記時消滅。判決離婚→確定時消滅。",relatedArticles:"民法§1049、§1050"}},
{id:"114-303-civil-39",explanation:{coreConcept:"胎兒收養與胎兒權利能力",analogy:"胎兒還沒出生就被收養→收養契約可撤銷（§1079之4）。胎兒受侵害→出生後才能請求賠償。B正確。",optionAnalysis:{A:"錯誤",B:"正確（本題答案）",C:"錯誤",D:"錯誤"},keyTakeaway:"§7胎兒以將來非死產者為限有權利能力。收養須出生後始有效。",relatedArticles:"民法§7、§1079"}},
{id:"114-303-civil-40",explanation:{coreConcept:"變更姓氏之聲請要件",analogy:"想改姓→要有法定事由才能向法院聲請。§1059第5項各款。父母離婚但約定共同行使→不符變更要件。C正確。",optionAnalysis:{A:"得聲請",B:"得聲請",C:"正確（本題答案-不得）",D:"得聲請"},keyTakeaway:"§1059第5項變更姓氏事由：生死不明3年↑、離婚改定、遺棄等。共同行使→不符。",relatedArticles:"民法§1059"}},
{id:"114-303-civil-41",explanation:{coreConcept:"收養終止後之婚姻禁止",analogy:"甲收養乙→乙叫甲媽媽→甲跟丙結婚→乙跟丙有姻親關係。即使收養終止→乙的前妻丁跟丙→禁婚？B無效依官方。",optionAnalysis:{A:"錯誤",B:"正確（本題答案）-無效",C:"錯誤",D:"錯誤"},keyTakeaway:"§983禁婚親：直系姻親→即使離婚/收養終止仍不得結婚。",relatedArticles:"民法§983"}},
{id:"114-303-civil-42",explanation:{coreConcept:"遺產酌給應由法院決定",analogy:"被繼承人生前養的人想分遺產→不是管理人說了算→要法院決定。C說由管理人決定→錯！",optionAnalysis:{A:"正確",B:"正確",C:"錯誤（本題答案）-應由法院決定",D:"正確"},keyTakeaway:"§1149遺產酌給→由親屬會議依其所受扶養程度酌給。非管理人決定。",relatedArticles:"民法§1149、§1179"}},
{id:"114-303-civil-43",explanation:{coreConcept:"未成年人監護人之指定",analogy:"媽媽遺囑指定丁當監護人→爸爸受監護宣告不能行使親權→丁成為丙的監護人。B正確。",optionAnalysis:{A:"錯誤-甲受監護宣告",B:"正確（本題答案）",C:"錯誤",D:"錯誤"},keyTakeaway:"§1093遺囑指定監護人優先。父母一方不能行使親權→他方行使；都不能→遺囑指定。",relatedArticles:"民法§1093、§1094"}},
{id:"114-303-civil-44",explanation:{coreConcept:"繼承之相關規定",analogy:"依官方答案。繼承法各論題目。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"繼承相關規定需依具體題目分析。",relatedArticles:"民法§1138-§1176"}},
{id:"114-303-civil-45",explanation:{coreConcept:"遺囑之方式與效力",analogy:"依官方答案。遺囑法各論題目。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"遺囑五種方式：自書、公證、密封、代筆、口授。方式不符→無效。",relatedArticles:"民法§1189-§1198"}},
{id:"114-303-civil-46",explanation:{coreConcept:"特留分之計算",analogy:"依官方答案。特留分計算題目。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"§1223特留分：直系卑親屬→應繼分½。父母→應繼分½。配偶→應繼分½。",relatedArticles:"民法§1223、§1224"}},
{id:"114-303-civil-47",explanation:{coreConcept:"繼承回復請求權",analogy:"依官方答案。繼承回復請求權時效與效力。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"§1146繼承回復請求權：知悉2年、繼承開始10年。",relatedArticles:"民法§1146"}},
{id:"114-303-civil-48",explanation:{coreConcept:"遺產分割之效力",analogy:"依官方答案。遺產分割相關規定。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"§1164遺產分割：繼承人得隨時請求分割。遺囑禁止→最長10年。",relatedArticles:"民法§1164、§1165"}},
{id:"114-303-civil-49",explanation:{coreConcept:"限定繼承與概括繼承",analogy:"依官方答案。繼承之限定與拋棄。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"§1148概括繼承限定責任：以遺產為限負清償責任。拋棄→3個月內。",relatedArticles:"民法§1148、§1174"}},
{id:"114-303-civil-50",explanation:{coreConcept:"侵權行為損害賠償",analogy:"依官方答案。侵權行為與損害賠償之相關規定。",optionAnalysis:{A:"依官方答案",B:"依官方答案",C:"依官方答案",D:"依官方答案"},keyTakeaway:"§184侵權行為：故意過失不法侵害他人權利→負損害賠償。§191之3危險責任。",relatedArticles:"民法§184、§185、§191之3"}}
];
async function run(){for(const e of E){await db.collection('questions').doc(e.id).set({explanation:e.explanation},{merge:true});console.log('OK',e.id);}console.log('Done: civil Q26-50');process.exit();}
run();
